import img1 from "../img/gallery/gallery-1.jpg";
import img2 from "../img/gallery/gallery-2.jpg";
import img3 from "../img/gallery/gallery-3.jpg";
import img4 from "../img/gallery/gallery-4.jpg";

const Products = [
    {
        id: 1,
        name: "Product One",
        category: "cream",
        price: 950,
        imgSrc: img1,
        description: `-lorem ipsum dolr magic as we know it too 
         -Works like magic, doesnt go bad `,
        quantity: 10,
    },
    {
        id: 2,
        name: "Product Two",
        category: "perfume",
        price: 1950,
        imgSrc: img2,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 5,
    },
    {
        id: 3,
        name: "Product three",
        category: "rollon",
        price: 750,
        imgSrc: img3,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 14,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
    {
        id: 4,
        name: "Product Two",
        category: "cream",
        price: 1250,
        imgSrc: img4,
        description: "lorem ipsum dolr magic as we know it too",
        quantity: 3,
    },
];

export default Products;
